name: Publish Package

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get full repo history
      uses: actions/checkout@v3
      with:
        # 0 here means 'all history'.
        # we need at least the current 'height' in order for Nerdbank to work
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
        global-json-file: 'global.json' # in addition to the 6.0 we need for tests, install "latest"
    - name: Release
      run: dotnet build --configuration release
    - name: Publish
      run: dotnet nuget push "Microsoft.NET.Build.Containers/bin/Release/Microsoft.NET.Build.Containers.*.nupkg" --api-key ${{ secrets.FEED_UPLOAD_TOKEN }} --source "https://nuget.pkg.github.com/rainersigwald/index.json"
